name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Verifica o repositório
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-vesion: 'latest'
        chromedriver-version: 'latest'

    # Configura o Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4' # Substitua pela versão do Python usada no projeto

    # Instala as dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    # Executa os testes
    - name: Run tests
      run: |
        pytest
